files = [
	"stream/assets/*"
]

[meta]
"stream/carcols.meta" = "CARCOLS_FILE"
"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
"stream/handling.meta" = "HANDLING_FILE"
#"stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"
"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"

"stream/audio/sfx/dlc_rotary7" = "AUDIO_WAVEPACK"
"stream/audio/rotary7_game.dat" = "AUDIO_GAMEDATA"
"stream/audio/rotary7_sounds.dat" = "AUDIO_SOUNDDATA"
#	"stream/audio/rotary7_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
"fd" = "Mazda RX7"