files = [
	"stream/assets/*"
]

[meta]
	"stream/carcols.meta" = "CARCOLS_FILE"
	"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
	"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
	"stream/handling.meta" = "HANDLING_FILE"
	"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"
	# "stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"

	"stream/audio/sfx/dlc_agerarsv2" = "AUDIO_WAVEPACK"
	"stream/audio/agerarsv2_game.dat" = "AUDIO_GAMEDATA"
	"stream/audio/agerarsv2_sounds.dat" = "AUDIO_SOUNDDATA"
	# "stream/audio/agerarsv2_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
	"jesko" = "Koenigsegg Jesko"
