type = "js"
main = "server/server.js"
server-files = [
    "server/*",
    "garageList.js"
]
client-main = "client/client.js"
client-files = [
    "client/*",
    "garageList.js"
]
deps = [
    "carManager"
]
