

export const vehicleList = {
    huracan_spyder: 'huracans',
    huracan_p: 'huracanp',
    r8_2008: 'r8',
    r8_2016: 'r8v10',
    chiron: '2017chiron',
    chiron_ss: '2019chiron',
    giulia_gta: 'gtam21',
    giulia: 'giulia',
    skyline: 'Skyline',
    countach: 'lpi8004',
    r6: 'r6',
    italia_458: 'italia458',
    centenario: 'lp770',
    mustang_gt: 'MGT',
    
}


export const tireBrand = [
    "Aucune",
    "Atomic Blanc",
    "Atomic Jaune",
    "Fukaru Blanc",
    "Fukaru Rouge",
    "Chepalle Jaune",
    "Chepalle Vert"
]

export const tireColor = [
    "Aucune",
    "Blanc Fin",
    "Blanc Moyen",
    "Blanc Large",
    "Rouge Fin",
    "Bleu Fin",
    "Atomic Blanc"
]

export const wheelTypeList = [
    {name: "Sport", range: 53},
    {name: "Muscle", range: 36},
    {name: "Lowrider", range: 30},
    {name: "SUV", range: 38},
    {name: "Tout Terrain", range: 35},
    {name: "Tuner", range: 48},
    {name: "Moto", range: 48},
    {name: "Haut de Gamme", range: 40},
    {name: "Rue", range: 31, extra: tireColor},             //217
    {name: "Rue Rouillées", range: 31, extra: tireColor},   //217
    {name: "Circuit", range: 20, extra: tireBrand},         //140
    {name: "Tunning 1", range: 30, extra: tireBrand},       //210
    {name: "Tunning 2", range: 30, extra: tireBrand}        //210
]

export const modList = [
    "Spoilers",
    "Front Bumper",
    "Rear Bumper",
    "Side skirt",
    "Exhaust",
    "Frame",
    "Grille",
    "Bonnet",
    "Left Wing",
    "Right wing",
    "Roof",
    "Engine",
    "Brakes",
    "Transmission",
    "Horns",
    "Suspension",
    "Armor",
    "",
    "Turbo",
    "",
    "Custom tire smoke",
    "",
    "Xenon",
    "Front Wheels",
    "Back Wheels",
    "Plate holders",
    "Plate vanity",
    "Trim Design",
    "Ornaments",
    "",
    "Dial Design",
    "Door interior",
    "Seats",
    "Steering Wheel",
    "Shift Lever",
    "Plaques",
    "Rear shelf",
    "Trunk",
    "Hydraulics",
    "Engine block",
    "Air filter",
    "Strut bar",
    "Arch Cover",
    "Antenna",
    "Exterior parts",
    "Tank",
    "Door",
    "WHEELS_REAR_OR_HYDRAULICS",
    "Livery",
]


export const plateList = [
    "Bleu sur Blanc 1",
    "Jaune sur Noir",
    "Jaune sur Bleu",
    "Bleu sur Blanc 2",
    "Bleu sur Blanc 3",
    "Yankton"
]


const Mod = ['supra', 'rx7', '370z', 'gt86', 'gtr', 'h2r', 's1000rr', 'i8', 'rs7', 'huracanspyder', 'huracanp', 'r8', 'r8spyder', 'p1', 'vanquish', 'chiron', 'chironss', ]
const Sport = [ 'alpha', 'banshee', 'bestiagts', 'blista2', 'blista3', 'buffalo2', 'buffalo3', 'carbonizzare', 'comet2', 'comet3', 'comet4', 'comet5', 'coquette', 'coquette4', 'drafter', 'elegy', 'elegy2', 'feltzer2', 'flashgt', 'furoregt', 'fusilade', 'futo', 'gb200', 'hotring', 'imorgon', 'issi7', 'italigto', 'italirsx', 'jester', 'jester2', 'jester3', 'jugular', 'khamelion', 'koModa', 'kuruma', 'kuruma2', 'locust', 'lynx', 'massacro', 'massacro2', 'neo', 'neon', 'ninef', 'ninef2', 'omnis', 'paragon', 'paragon2', 'pariah', 'penumbra', 'penumbra2', 'raiden', 'rapidgt', 'rapidgt2', 'raptor', 'revolter', 'ruston', 'schafter3', 'schafter4', 'schlagen', 'schwarzer', 'Schwartzer', 'sentinel3', 'seven70', 'specter', 'specter2', 'streiter', 'sugoi', 'sultan', 'sultan2', 'surano', 'tampa2', 'tropos', 'verlierer2', 'veto', 'veto2', 'vstr', 'zr380', 'zr3802', 'zr3803', ]
const SportClassic = ['ardent', 'btype', 'btype2', 'btype3', 'casco', 'cheburek', 'cheetah2', 'coquette2', 'deluxo', 'dynasty', 'fagaloa', 'feltzer3', 'gt500', 'infernus2', 'jb700', 'jb7002', 'mamba', 'manana', 'michelli', 'monroe', 'nebula', 'peyote', 'peyote3', 'pigalle', 'rapidgt3', 'retinue', 'retinue2', 'savestra', 'stinger', 'stingergt', 'stromberg', 'swinger', 'toreador', 'torero', 'tornado', 'tornado2', 'tornado3', 'tornado4', 'tornado5', 'tornado6', 'turismo2', 'viseris', 'z190', 'zion3', 'ztype', ]
const SuperCar = ['adder', 'autarch', 'banshee2', 'bullet', 'cheetah', 'cyclone', 'deveste', 'emerus', 'entity2', 'entityxf', 'fmj', 'furia', 'gp1', 'infernus', 'italigtb', 'italigtb2', 'krieger', 'le7b', 'nero', 'nero2', 'osiris', 'penetrator', 'pfister811', 'prototipo', 'reaper', 's80', 'sc1', 'scramjet', 'sheava', 'sultanrs', 't20', 'taipan', 'tempesta', 'tezeract', 'thrax', 'tigon', 'turismor', 'tyrant', 'tyrus', 'vacca', 'vagner', 'vigilante', 'visione', 'voltic', 'voltic2', 'xa21', 'zentorno', 'zorrusso', ]
const Suv = ['baller', 'baller2', 'baller3', 'baller4', 'baller5', 'baller6', 'bjxl', 'cavalcade', 'cavalcade2', 'contender', 'dubsta', 'dubsta2', 'fq2', 'granger', 'gresley', 'habanero', 'huntley', 'landstalker', 'landstalker2', 'mesa', 'mesa2', 'novak', 'patriot', 'patriot2', 'radi', 'rebla', 'rocoto', 'seminole', 'seminole2', 'serrano', 'squaddie', 'toros', 'xls', 'xls2', ]
const Van = ['bison', 'bison2', 'bison3', 'bobcatxl', 'boxville', 'boxville2', 'boxville3', 'boxville4', 'boxville5', 'burrito', 'burrito2', 'burrito3', 'burrito4', 'burrito5', 'camper', 'gburrito', 'gburrito2', 'journey', 'minivan', 'minivan2', 'paradise', 'pony', 'pony2', 'rumpo', 'rumpo2', 'rumpo3', 'speedo', 'speedo2', 'speedo4', 'surfer', 'surfer2', 'taco', 'youga', 'youga2', 'youga3', ]
const Muscle = ['blade', 'buccaneer', 'buccaneer2', 'chino', 'chino2', 'clique', 'coquette3', 'deviant', 'dominator', 'dominator2', 'dominator3', 'dominator4', 'dominator5', 'dominator6', 'dukes', 'dukes2', 'dukes3', 'ellie', 'faction', 'faction2', 'faction3', 'gauntlet', 'gauntlet2', 'gauntlet3', 'gauntlet4', 'gauntlet5', 'hermes', 'hotknife', 'hustler', 'impaler', 'impaler2', 'impaler3', 'impaler4', 'imperator', 'imperator2', 'imperator3', 'lurcher', 'manana2', 'moonbeam', 'moonbeam2', 'nightshade', 'peyote2', 'phoenix', 'picador', 'ratloader', 'ratloader2', 'ruiner', 'ruiner2', 'ruiner3', 'sabregt', 'sabregt2', 'slamvan', 'slamvan2', 'slamvan3', 'slamvan4', 'slamvan5', 'slamvan6', 'stalion', 'stalion2', 'tampa', 'tampa3', 'tulip', 'vamos', 'vigero', 'virgo', 'virgo2', 'virgo3', 'voodoo', 'voodoo2', 'yosemite', 'yosemite2', ]
const Offroad = ['bfinjection', 'bifta', 'blazer', 'blazer2', 'blazer3', 'blazer4', 'blazer5', 'bodhi2', 'brawler', 'bruiser', 'bruiser2', 'bruiser3', 'brutus', 'brutus2', 'brutus3', 'caracara', 'caracara2', 'dloader', 'dubsta3', 'mphipster', 'dune', 'dune2', 'dune3', 'dune4', 'dune5', 'everon', 'freecrawler', 'hellion', 'insurgent', 'insurgent2', 'insurgent3', 'kalahari', 'kamacho', 'marshall', 'menacer', 'mesa3', 'monster', 'monster3', 'monster4', 'monster5', 'nightshark', 'outlaw', 'rancherxl', 'rancherxl2', 'rcbandito', 'rebel', 'rebel2', 'riata', 'sandking', 'sandking2', 'technical', 'technical2', 'technical3', 'trophytruck', 'trophytruck2', 'vagrant', 'verus', 'winky', 'yosemite3', 'zhaba', ]
const Sedan = ['asea', 'asea2', 'asterope', 'cog55', 'cog552', 'cognoscenti', 'cognoscenti2', 'emperor', 'emperor2', 'emperor3', 'fugitive', 'glendale', 'glendale2', 'ingot', 'intruder', 'limo2', 'premier', 'primo', 'primo2', 'regina', 'romero', 'schafter2', 'schafter5', 'schafter6', 'stafford', 'stanier', 'stratum', 'stretch', 'superd', 'surge', 'tailgater', 'warrener', 'washington', ]
const Coupe = ['cogcabrio', 'exemplar', 'f620', 'felon', 'felon2', 'jackal', 'oracle', 'oracle2', 'sentinel', 'sentinel2', 'windsor', 'windsor2', 'zion', 'zion2', ]
const Compact = ['asbo', 'blista', 'brioso', 'club', 'dilettante', 'dilettante2', 'issi2', 'kanjo', 'panto', 'prairie', 'rhapsody', 'brioso2', 'issi3', 'issi4', 'issi5', 'issi6', 'weevil', ]
const Cycle = ['bmx', 'cruiser', 'fixter', 'scorcher', 'tribike', 'tribike2', 'tribike3', ]
const Emergency = ['ambulance', 'fbi', 'fbi2', 'firetruk', 'lguard', 'pbus', 'police', 'police2', 'police3', 'police4', 'policeb', 'policeold1', 'policeold2', 'policet', 'pranger', 'riot', 'riot2', 'sheriff', 'sheriff2', ]
const Helicopter = ['akula', 'annihilator', 'annihilator2', 'buzzard', 'buzzard2', 'cargobob', 'cargobob2', 'cargobob3', 'cargobob4', 'frogger', 'frogger2', 'havok', 'hunter', 'maverick', 'polmav', 'savage', 'seasparrow', 'seasparrow2', 'seasparrow3', 'skylift', 'supervolito', 'supervolito2', 'swift', 'swift2', 'valkyrie', 'valkyrie2', 'volatus', ]
const Plane = ['alkonost', 'alphaz1', 'avenger', 'avenger2', 'bestra', 'blimp', 'blimp2', 'blimp3', 'bombushka', 'cargoplane', 'cuban800', 'dodo', 'duster', 'howard', 'hydra', 'jet', 'lazer', 'luxor', 'luxor2', 'mammatus', 'microlight', 'miljet', 'mogul', 'molotok', 'nimbus', 'nokota', 'pyro', 'rogue', 'sealbreeze', 'shamal', 'starling', 'strikeforce', 'stunt', 'titan', 'tula', 'velum', 'velum2', 'vestra', 'volatol', ]
const Boat = ['avisa', 'dinghy', 'dinghy2', 'dinghy3', 'dinghy4', 'dinghy5', 'jetmax', 'kosatka', 'longfin', 'marquis', 'patrolboat', 'predator', 'seashark', 'seashark2', 'seashark3', 'speeder', 'speeder2', 'squalo', 'submersible', 'submersible2', 'suntrap', 'toro', 'toro2', 'tropic', 'tropic2', 'tug', ]
const Industrial = ['bulldozer', 'cutter', 'dump', 'flatbed', 'guardian', 'handler', 'mixer', 'mixer2', 'rubble', 'tiptruck', 'tiptruck2', ]
const Service = ['aribus', 'brickade', 'bus', 'coach', 'pbus2', 'rallytruck', 'rentalbus', 'taxi', 'tourbus', 'trash', 'trash2', 'wastelander', ]
const Commercial = ['benson', 'biff', 'cerberus', 'cerberus2', 'cerberus3', 'hauler', 'hauler2', 'mule', 'mule2', 'mule3', 'mule4', 'packer', 'phantom', 'phantom2', 'phantom3', 'pounder', 'pounder2', 'stockade', 'stockade3', 'terbyte', ]
const Military = ['apc', 'barracks', 'barracks2', 'barracks3', 'barrage', 'chernobog', 'crusader', 'halftrack', 'khanjali', 'minitank', 'rhino', 'scarab', 'scarab2', 'scarab3', 'thruster', 'trailersmall2', 'vetir', ]
const Motorcycle = ['akuma', 'avarus', 'bagger', 'bati', 'bati2', 'bf400', 'carbonrs', 'chimera', 'cliffhanger', 'daemon', 'daemon2', 'deathbike', 'deathbike2', 'deathbike3', 'defiler', 'diablous', 'diablous2', 'double', 'enduro', 'esskey', 'faggio', 'faggio2', 'faggio3', 'fcr', 'fcr2', 'gargoyle', 'hakuchou', 'hakuchou2', 'hexer', 'innovation', 'lectro', 'manchez', 'manchez2', 'nemesis', 'nightblade', 'oppressor', 'oppressor2', 'pcj', 'ratbike', 'rrocket', 'ruffian', 'sanchez', 'sanchez2', 'sanctus', 'shotaro', 'sovereign', 'stryder', 'thrust', 'vader', 'vindicator', 'vortex', 'wolfsbane', 'zombiea', 'zombieb', ]
const F1 = ['formula', 'formula2', 'openwheel1', 'openwheel2', ]
export let carListByType = { Mod: Mod, Sport: Sport, SportClassic: SportClassic, Supercar: SuperCar, Suv: Suv, Van: Van, Muscle: Muscle, Offroad: Offroad, Sedan: Sedan, Coupe: Coupe, Compact: Compact, Motorcycle: Motorcycle, F1: F1, Cycle: Cycle, Emergency: Emergency, Helicopter: Helicopter, Plane: Plane, Boat: Boat, Industrial: Industrial, Service: Service, Commercial: Commercial, Military: Military}


export const xenonColors =  [
    "Série",
    "Xenon",
    "Blanc",
    "Bleu",
    "Bleu Clair",
    "Vert",
    "Vert Clair",
    "Jaune Clair",
    "Jaune",
    "Orange",
    "Rouge",
    "Rose Clair",
    "Rose",
    "Violet",
    "Noir"
]

export const windowTints = [
    "Teinté",
    "Limousine",
    "Foncé",
    "Clair",
    "Aucun"
]


export const serverColors = [
    {index: 0, hex: 'FF080808', name: 'Metallic Black', client: [1, 0]},
    {index: 1, hex: 'FF0F0F0F', name: 'Metallic Graphite Black', client: [1, 2]},
    {index: 2, hex: 'FF1C1E21', name: 'Metallic Black Steal', client: [1, 4]},
    {index: 3, hex: 'FF292C2E', name: 'Metallic Dark Silver', client: [1, 5]},
    {index: 4, hex: 'FF5A5E66', name: 'Metallic Silver', client: [1, 6]},
    {index: 5, hex: 'FF777C87', name: 'Metallic Blue Silver', client: [1, 7]},
    {index: 6, hex: 'FF515459', name: 'Metallic Steel Gray', client: [1, 8]},
    {index: 7, hex: 'FF323B47', name: 'Metallic Shadow Silver', client: [1, 9]},
    {index: 8, hex: 'FF333333', name: 'Metallic Stone Silver', client: [1, 10]},
    {index: 9, hex: 'FF1F2226', name: 'Metallic Midnight Silver', client: [1, 11]},
    {index: 10, hex: 'FF23292E', name: 'Metallic Gun Metal', client: [1, 12]},
    {index: 11, hex: 'FF121110', name: 'Metallic Anthracite Grey', client: [1, 3]},
    {index: 12, hex: 'FF050505', name: 'Matte Black', client: [3, 0] },
    {index: 13, hex: 'FF121212', name: 'Matte Gray', client: [3, 1] },
    {index: 14, hex: 'FF2F3233', name: 'Matte Light Grey', client: [3, 2]},
    {index: 15, hex: 'FF080808', name: 'Util Black'},
    {index: 16, hex: 'FF121212', name: 'Util Black Poly'},
    {index: 17, hex: 'FF202224', name: 'Util Dark silver'},
    {index: 18, hex: 'FF575961', name: 'Util Silver'},
    {index: 19, hex: 'FF23292E', name: 'Util Gun Metal'},
    {index: 20, hex: 'FF323B47', name: 'Util Shadow Silver'},
    {index: 21, hex: 'FF0F1012', name: 'Worn Black'},
    {index: 22, hex: 'FF212121', name: 'Worn Graphite'},
    {index: 23, hex: 'FF5B5D5E', name: 'Worn Silver Grey'},
    {index: 24, hex: 'FF888A99', name: 'Worn Silver'},
    {index: 25, hex: 'FF697187', name: 'Worn Blue Silver'},
    {index: 26, hex: 'FF3B4654', name: 'Worn Shadow Silver'},
    {index: 27, hex: 'FF690000', name: 'Metallic Red', client: [1, 13]},
    {index: 28, hex: 'FF8A0B00', name: 'Metallic Torino Red', client: [1, 14]},
    {index: 29, hex: 'FF6B0000', name: 'Metallic Formula Red', client: [1, 15]},
    {index: 30, hex: 'FF611009', name: 'Metallic Blaze Red', client: [1, 17]},
    {index: 31, hex: 'FF4A0A0A', name: 'Metallic Graceful Red', client: [1, 18]},
    {index: 32, hex: 'FF470E0E', name: 'Metallic Garnet Red', client: [1, 19]},
    {index: 33, hex: 'FF380C00', name: 'Metallic Desert Red', client: [1, 20]},
    {index: 34, hex: 'FF26030B', name: 'Metallic Cabernet Red', client: [1, 21]},
    {index: 35, hex: 'FF630012', name: 'Metallic Candy Red', client: [1, 23]},
    {index: 36, hex: 'FF802800', name: 'Metallic Sunrise Orange', client: [1, 27]},
    {index: 37, hex: 'FF6E4F2D', name: 'Metallic Classic Gold', client: [0, 30]},
    {index: 38, hex: 'FFBD4800', name: 'Metallic Orange', client: [1, 28]},
    {index: 39, hex: 'FF780000', name: 'Matte Red', client: [3, 9] },
    {index: 40, hex: 'FF360000', name: 'Matte Dark Red', client: [3, 10]},
    {index: 41, hex: 'FFAB3F00', name: 'Matte Orange', client: [3, 11]},
    {index: 42, hex: 'FFDE7E00', name: 'Matte Yellow', client: [3, 12]},
    {index: 43, hex: 'FF520000', name: 'Util Red'},
    {index: 44, hex: 'FF8C0404', name: 'Util Bright Red'},
    {index: 45, hex: 'FF4A1000', name: 'Util Garnet Red'},
    {index: 46, hex: 'FF592525', name: 'Worn Red'},
    {index: 47, hex: 'FF754231', name: 'Worn Golden Red'},
    {index: 48, hex: 'FF210804', name: 'Worn Dark Red'},
    {index: 49, hex: 'FF001207', name: 'Metallic Dark Green', client: [1, 35]},
    {index: 50, hex: 'FF001A0B', name: 'Metallic Racing Green', client: [1, 36]},
    {index: 51, hex: 'FF00211E', name: 'Metallic Sea Green', client: [1, 37]},
    {index: 52, hex: 'FF1F261E', name: 'Metallic Olive Green', client: [1, 38]},
    {index: 53, hex: 'FF003805', name: 'Metallic Green', client: [1, 39]},
    {index: 54, hex: 'FF0B4145', name: 'Metallic Gasoline Blue Green', client: [1, 40]},
    {index: 55, hex: 'FF418503', name: 'Matte Lime Green', client: [3, 13]},
    {index: 56, hex: 'FF0F1F15', name: 'Util Dark Green'},
    {index: 57, hex: 'FF023613', name: 'Util Green'},
    {index: 58, hex: 'FF162419', name: 'Worn Dark Green'},
    {index: 59, hex: 'FF2A3625', name: 'Worn Green'},
    {index: 60, hex: 'FF455C56', name: 'Worn Sea Wash'},
    {index: 61, hex: 'FF000D14', name: 'Metallic Midnight Blue', client: [1, 43]},
    {index: 62, hex: 'FF001029', name: 'Metallic Dark Blue', client: [1, 44]},
    {index: 63, hex: 'FF1C2F4F', name: 'Metallic Saxony Blue', client: [1, 45]},
    {index: 64, hex: 'FF001B57', name: 'Metallic Blue', client: [1, 46]},
    {index: 65, hex: 'FF3B4E78', name: 'Metallic Mariner Blue', client: [1, 47]},
    {index: 66, hex: 'FF272D3B', name: 'Metallic Harbor Blue', client: [1, 48]},
    {index: 67, hex: 'FF95B2DB', name: 'Metallic Diamond Blue', client: [1, 49]},
    {index: 68, hex: 'FF3E627A', name: 'Metallic Surf Blue', client: [1, 50]},
    {index: 69, hex: 'FF1C3140', name: 'Metallic Nautical Blue', client: [1, 51]},
    {index: 70, hex: 'FF0055C4', name: 'Metallic Bright Blue', client: [1, 53]},
    {index: 71, hex: 'FF1A182E', name: 'Metallic Purple Blue', client: [1, 68]},
    {index: 72, hex: 'FF161629', name: 'Metallic Spinnaker Blue', client: [1, 69]},
    {index: 73, hex: 'FF0E316D', name: 'Metallic Ultra Blue', client: [1, 52]},
    {index: 74, hex: 'FF395A83', name: 'Metallic Bright Blue', client: [1, 54]},
    {index: 75, hex: 'FF09142E', name: 'Util Dark Blue'},
    {index: 76, hex: 'FF0F1021', name: 'Util Midnight Blue'},
    {index: 77, hex: 'FF152A52', name: 'Util Blue'},
    {index: 78, hex: 'FF324654', name: 'Util Sea Foam Blue'},
    {index: 79, hex: 'FF152563', name: 'Uil Lightning blue'},
    {index: 80, hex: 'FF223BA1', name: 'Util Maui Blue Poly'},
    {index: 81, hex: 'FF1F1FA1', name: 'Util Bright Blue'},
    {index: 82, hex: 'FF030E2E', name: 'Matte Dark Blue', client: [3, 5]},
    {index: 83, hex: 'FF0F1E73', name: 'Matte Blue', client: [3, 4] },
    {index: 84, hex: 'FF001C32', name: 'Matte Midnight Blue', client: [3, 6]},
    {index: 85, hex: 'FF2A3754', name: 'Worn Dark blue'},
    {index: 86, hex: 'A0303C5E', name: 'Worn Blue'},
    {index: 87, hex: 'FF3B6796', name: 'Worn Light blue'},
    {index: 88, hex: 'FFF5890F', name: 'Metallic Taxi Yellow', client: [1, 32]},
    {index: 89, hex: 'FFD9A600', name: 'Metallic Race Yellow', client: [1, 33]},
    {index: 90, hex: 'FF4A341B', name: 'Metallic Bronze', client: [1, 31]},
    {index: 91, hex: 'FFA2A827', name: 'Metallic Yellow Bird', client: [1, 34]},
    {index: 92, hex: 'FF568F00', name: 'Metallic Lime', client: [1, 41]},
    {index: 93, hex: 'FF57514B', name: 'Metallic Champagne'},
    {index: 94, hex: 'FF291B06', name: 'Metallic Pueblo Beige', client: [1, 58]},
    {index: 95, hex: 'FF262117', name: 'Metallic Dark Ivory', client: [1, 57]},
    {index: 96, hex: 'FF120D07', name: 'Metallic Choco Brown', client: [1, 55]},
    {index: 97, hex: 'FF332111', name: 'Metallic Golden Brown', client: [1, 59]},
    {index: 98, hex: 'FF3D3023', name: 'Metallic Light Brown', client: [1, 62]},
    {index: 99, hex: 'FF5E5343', name: 'Metallic Straw Beige', client: [1, 65]},
    {index: 100, hex: 'FF37382B', name: 'Metallic Moss Brown', client: [1, 63]},
    {index: 101, hex: 'FF221918', name: 'Metallic Biston Brown', client: [1, 56]},
    {index: 102, hex: 'FF575036', name: 'Metallic Beechwood', client: [1, 64]},
    {index: 103, hex: 'FF241309', name: 'Metallic Dark Beechwood', client: [1, 60]},
    {index: 104, hex: 'FF3B1700', name: 'Metallic Choco Orange', client: [1, 61]},
    {index: 105, hex: 'FF6E6246', name: 'Metallic Beach Sand', client: [1, 66]},
    {index: 106, hex: 'FB998D73', name: 'Metallic Sun Bleeched Sand', client: [1, 67]},
    {index: 107, hex: 'FFCFC0A5', name: 'Metallic Cream', client: [1, 72]},
    {index: 108, hex: 'FF1F1709', name: 'Util Brown'},
    {index: 109, hex: 'FB3D311D', name: 'Util Medium Brown'},
    {index: 110, hex: 'FF665847', name: 'Util Light Brown'},
    {index: 111, hex: 'FFF0F0F0', name: 'Metallic White', client: [1, 73]},
    {index: 112, hex: 'FFB3B9C9', name: 'Metallic Frost White', client: [1, 74]},
    {index: 113, hex: 'FF615F55', name: 'Worn Honey Beige'},
    {index: 114, hex: 'FF241E1A', name: 'Worn Brown'},
    {index: 115, hex: 'FF171413', name: 'Worn Dark Brown'},
    {index: 116, hex: 'FF3B372F', name: 'Worn straw beige'},
    {index: 117, hex: 'FF3B4045', name: 'Brushed Steel', client: [4, 0]},
    {index: 118, hex: 'FF1A1E21', name: 'Brushed Black steel', client: [4, 1]},
    {index: 119, hex: 'FF5E646B', name: 'Brushed Aluminium', client: [4, 2]},
    {index: 120, hex: 'FF000000', name: 'Chrome', client: [5, 0] },
    {index: 121, hex: 'FFB0B0B0', name: 'Worn Off White'},
    {index: 122, hex: 'FF999999', name: 'Util Off White'},
    {index: 123, hex: 'FFB56519', name: 'Worn Orange'},
    {index: 124, hex: 'FFC45C33', name: 'Worn Light Orange'},
    {index: 125, hex: 'FF47783C', name: 'Metallic Securicor Green'},
    {index: 126, hex: 'FFBA8425', name: 'Worn Taxi Yellow'},
    {index: 127, hex: 'FF2A77A1', name: 'police car blue'},
    {index: 128, hex: 'FF243022', name: 'Matte Green', client: [3, 14]},
    {index: 129, hex: 'FF6B5F54', name: 'Matte Brown'},
    {index: 130, hex: 'FFC96E34', name: 'Worn Orange'},
    {index: 131, hex: 'FFD9D9D9', name: 'Matte White', client: [3, 3]},
    {index: 132, hex: 'FFF0F0F0', name: 'Worn White'},
    {index: 133, hex: 'FF3F4228', name: 'Worn Olive Army Green'},
    {index: 134, hex: 'FFFFFFFF', name: 'Pure White'},
    {index: 135, hex: 'FFB01259', name: 'Hot Pink', client: [1, 24] },
    {index: 136, hex: 'F69799', name: 'Salmon pink', client: [1, 26] },
    {index: 137, hex: 'FF8F2F55', name: 'Metallic Vermillion Pink', client: [1, 25]},
    {index: 138, hex: 'C26610', name: 'Orange', client: [1, 29] },
    {index: 139, hex: '69BD45', name: 'Green'},
    {index: 140, hex: '00AEEF', name: 'Blue'},
    {index: 141, hex: 'FF000108', name: 'Mettalic Black Blue', client: [1, 42]},
    {index: 142, hex: 'FF050008', name: 'Metallic Black Purple', client: [1, 70]},
    {index: 143, hex: 'FF080000', name: 'Metallic Black Red', client: [1, 22]},
    {index: 144, hex: '565751', name: 'hunter green'},
    {index: 145, hex: '320642', name: 'Metallic Purple', client: [1, 71]},
    {index: 146, hex: 'FF00080F', name: 'Metaillic V Dark Blue', client: [0, 70]},
    {index: 147, hex: 'FF080808', name: 'MODSHOP BLACK1', client: [1, 1]},
    {index: 148, hex: '320642', name: 'Matte Purple', client: [3, 8] },
    {index: 149, hex: 'FF050008', name: 'Matte Dark Purple', client: [3, 7]},
    {index: 150, hex: 'FF6B0B00', name: 'Metallic Lava Red', client: [1, 16]},
    {index: 151, hex: 'FF121710', name: 'Matte Forest Green', client: [3, 15]},
    {index: 152, hex: 'FF323325', name: 'Matte Olive Drab', client: [3, 17]},
    {index: 153, hex: 'FF3B352D', name: 'Matte Desert Brown', client: [3, 18]},
    {index: 154, hex: 'FF706656', name: 'Matte Desert Tan', client: [3, 19]},
    {index: 155, hex: 'FF2B302B', name: 'Matte Foilage Green', client: [3, 16]},
    {index: 156, hex: 'FF414347', name: 'DEFAULT ALLOY COLOR'},
    {index: 157, hex: 'FF6690B5', name: 'Epsilon Blue'},
    {index: 158, hex: 'FF47391B', name: 'MP100 GOLD', client: [4, 3] },
    {index: 159, hex: 'FF47391B', name: 'MP100 GOLD SATIN', client: [4, 4]},
    {index: 160, hex: 'FFFFD859', name: 'MP100 GOLD SPEC' }
  ]


export const colors = [
    {
        index: 0,
        name: "Normal",
        count: 75,
        colors: [
            {index: 0, name: "BLACK", server: 0},
            {index: 1, name: "BLACK_GRAPHITE", server: 147},
            {index: 2, name: "GRAPHITE", server: 1},
            {index: 3, name: "ANTHR_BLACK", server: 11},
            {index: 4, name: "BLACK_STEEL", server: 2},
            {index: 5, name: "DARK_SILVER", server: 3},
            {index: 6, name: "SILVER", server: 4},
            {index: 7, name: "BLUE_SILVER", server: 5},
            {index: 8, name: "ROLLED_STEEL", server: 6},
            {index: 9, name: "SHADOW_SILVER", server: 7},
            {index: 10, name: "STONE_SILVER", server: 8},
            {index: 11, name: "MIDNIGHT_SILVER", server: 9},
            {index: 12, name: "CAST_IRON_SIL", server: 10},
            {index: 13, name: "RED", server: 27},
            {index: 14, name: "TORINO_RED", server: 28},
            {index: 15, name: "FORMULA_RED", server: 29},
            {index: 16, name: "LAVA_RED", server: 150},
            {index: 17, name: "BLAZE_RED", server: 30},
            {index: 18, name: "GRACE_RED", server: 31},
            {index: 19, name: "GARNET_RED", server: 32},
            {index: 20, name: "SUNSET_RED", server: 33},
            {index: 21, name: "CABERNET_RED", server: 34},
            {index: 22, name: "WINE_RED", server: 143},
            {index: 23, name: "CANDY_RED", server: 35},
            {index: 24, name: "HOT_PINK", server: 135},
            {index: 25, name: "PINK", server: 137},
            {index: 26, name: "SALMON_PINK", server: 136},
            {index: 27, name: "SUNRISE_ORANGE", server: 36},
            {index: 28, name: "ORANGE", server: 38},
            {index: 29, name: "BRIGHT_ORANGE", server: 138},
            {index: 30, name: "GOLD", server: 37},
            {index: 31, name: "BRONZE", server: 90},
            {index: 32, name: "YELLOW", server: 88},
            {index: 33, name: "RACE_YELLOW", server: 89},
            {index: 34, name: "FLUR_YELLOW", server: 91},
            {index: 35, name: "DARK_GREEN", server: 49},
            {index: 36, name: "RACING_GREEN", server: 50},
            {index: 37, name: "SEA_GREEN", server: 51},
            {index: 38, name: "OLIVE_GREEN", server: 52},
            {index: 39, name: "BRIGHT_GREEN", server: 53},
            {index: 40, name: "PETROL_GREEN", server: 54},
            {index: 41, name: "LIME_GREEN", server: 92},
            {index: 42, name: "MIDNIGHT_BLUE", server: 141},
            {index: 43, name: "GALAXY_BLUE", server: 61},
            {index: 44, name: "DARK_BLUE", server: 62},
            {index: 45, name: "SAXON_BLUE", server: 63},
            {index: 46, name: "BLUE", server: 64},
            {index: 47, name: "MARINER_BLUE", server: 65},
            {index: 48, name: "HARBOR_BLUE", server: 66},
            {index: 49, name: "DIAMOND_BLUE", server: 67},
            {index: 50, name: "SURF_BLUE", server: 68},
            {index: 51, name: "NAUTICAL_BLUE", server: 69},
            {index: 52, name: "RACING_BLUE", server: 73},
            {index: 53, name: "ULTRA_BLUE", server: 70},
            {index: 54, name: "LIGHT_BLUE", server: 74},
            {index: 55, name: "CHOCOLATE_BROWN", server: 96},
            {index: 56, name: "BISON_BROWN", server: 101},
            {index: 57, name: "CREEK_BROWN", server: 95},
            {index: 58, name: "UMBER_BROWN", server: 94},
            {index: 59, name: "MAPLE_BROWN", server: 97},
            {index: 60, name: "BEECHWOOD_BROWN", server: 103},
            {index: 61, name: "SIENNA_BROWN", server: 104},
            {index: 62, name: "SADDLE_BROWN", server: 98},
            {index: 63, name: "MOSS_BROWN", server: 100},
            {index: 64, name: "WOODBEECH_BROWN", server: 102},
            {index: 65, name: "STRAW_BROWN", server: 99},
            {index: 66, name: "SANDY_BROWN", server: 105},
            {index: 67, name: "BLEECHED_BROWN", server: 106},
            {index: 68, name: "PURPLE", server: 71},
            {index: 69, name: "SPIN_PURPLE", server: 72},
            {index: 70, name: "MIGHT_PURPLE", server: 146},
            {index: 71, name: "BRIGHT_PURPLE", server: 145},
            {index: 72, name: "CREAM", server: 107},
            {index: 73, name: "WHITE", server: 111},
            {index: 74, name: "FROST_WHITE", server: 112}
        ]
    },
    
    {
        index: 1,
        name: "Metallic",
        count: 75,
        colors: [
            {index: 0, name: "BLACK", server: 0},
            {index: 1, name: "BLACK_GRAPHITE", server: 147},
            {index: 2, name: "GRAPHITE", server: 1},
            {index: 3, name: "ANTHR_BLACK", server: 11},
            {index: 4, name: "BLACK_STEEL", server: 2},
            {index: 5, name: "DARK_SILVER", server: 3},
            {index: 6, name: "SILVER", server: 4},
            {index: 7, name: "BLUE_SILVER", server: 5},
            {index: 8, name: "ROLLED_STEEL", server: 6},
            {index: 9, name: "SHADOW_SILVER", server: 7},
            {index: 10, name: "STONE_SILVER", server: 8},
            {index: 11, name: "MIDNIGHT_SILVER", server: 9},
            {index: 12, name: "CAST_IRON_SIL", server: 10},
            {index: 13, name: "RED", server: 27},
            {index: 14, name: "TORINO_RED", server: 28},
            {index: 15, name: "FORMULA_RED", server: 29},
            {index: 16, name: "LAVA_RED", server: 150},
            {index: 17, name: "BLAZE_RED", server: 30},
            {index: 18, name: "GRACE_RED", server: 31},
            {index: 19, name: "GARNET_RED", server: 32},
            {index: 20, name: "SUNSET_RED", server: 33},
            {index: 21, name: "CABERNET_RED", server: 34},
            {index: 22, name: "WINE_RED", server: 143},
            {index: 23, name: "CANDY_RED", server: 35},
            {index: 24, name: "HOT_PINK", server: 135},
            {index: 25, name: "PINK", server: 137},
            {index: 26, name: "SALMON_PINK", server: 136},
            {index: 27, name: "SUNRISE_ORANGE", server: 36},
            {index: 28, name: "ORANGE", server: 38},
            {index: 29, name: "BRIGHT_ORANGE", server: 138},
            {index: 30, name: "GOLD", server: 99},
            {index: 31, name: "BRONZE", server: 90},
            {index: 32, name: "YELLOW", server: 88},
            {index: 33, name: "RACE_YELLOW", server: 89},
            {index: 34, name: "FLUR_YELLOW", server: 91},
            {index: 35, name: "DARK_GREEN", server: 49},
            {index: 36, name: "RACING_GREEN", server: 50},
            {index: 37, name: "SEA_GREEN", server: 51},
            {index: 38, name: "OLIVE_GREEN", server: 52},
            {index: 39, name: "BRIGHT_GREEN", server: 53},
            {index: 40, name: "PETROL_GREEN", server: 54},
            {index: 41, name: "LIME_GREEN", server: 92},
            {index: 42, name: "MIDNIGHT_BLUE", server: 141},
            {index: 43, name: "GALAXY_BLUE", server: 61},
            {index: 44, name: "DARK_BLUE", server: 62},
            {index: 45, name: "SAXON_BLUE", server: 63},
            {index: 46, name: "BLUE", server: 64},
            {index: 47, name: "MARINER_BLUE", server: 65},
            {index: 48, name: "HARBOR_BLUE", server: 66},
            {index: 49, name: "DIAMOND_BLUE", server: 67},
            {index: 50, name: "SURF_BLUE", server: 68},
            {index: 51, name: "NAUTICAL_BLUE", server: 69},
            {index: 52, name: "RACING_BLUE", server: 73},
            {index: 53, name: "ULTRA_BLUE", server: 70},
            {index: 54, name: "LIGHT_BLUE", server: 74},
            {index: 55, name: "CHOCOLATE_BROWN", server: 96},
            {index: 56, name: "BISON_BROWN", server: 101},
            {index: 57, name: "CREEK_BROWN", server: 95},
            {index: 58, name: "UMBER_BROWN", server: 94},
            {index: 59, name: "MAPLE_BROWN", server: 97},
            {index: 60, name: "BEECHWOOD_BROWN", server: 103},
            {index: 61, name: "SIENNA_BROWN", server: 104},
            {index: 62, name: "SADDLE_BROWN", server: 98},
            {index: 63, name: "MOSS_BROWN", server: 100},
            {index: 64, name: "WOODBEECH_BROWN", server: 102},
            {index: 65, name: "STRAW_BROWN", server: 99},
            {index: 66, name: "SANDY_BROWN", server: 105},
            {index: 67, name: "BLEECHED_BROWN", server: 106},
            {index: 68, name: "PURPLE", server: 71},
            {index: 69, name: "SPIN_PURPLE", server: 72},
            {index: 70, name: "MIGHT_PURPLE", server: 142},
            {index: 71, name: "BRIGHT_PURPLE", server: 145},
            {index: 72, name: "CREAM", server: 107},
            {index: 73, name: "WHITE", server: 111},
            {index: 74, name: "FROST_WHITE", server: 112}
        ]
    },

    {
        index: 2,
        name: "Pearl",
        count: 74,
        pearlColors: serverColors,
        colors: [
            {index: 0, name: "BLACK_GRAPHITE", server: 147},
            {index: 1, name: "GRAPHITE", server: 1},
            {index: 2, name: "ANTHR_BLACK", server: 11},
            {index: 3, name: "BLACK_STEEL", server: 2},
            {index: 4, name: "DARK_SILVER", server: 3},
            {index: 5, name: "SILVER", server: 4},
            {index: 6, name: "BLUE_SILVER", server: 5},
            {index: 7, name: "ROLLED_STEEL", server: 6},
            {index: 8, name: "SHADOW_SILVER", server: 7},
            {index: 9, name: "STONE_SILVER", server: 8},
            {index: 10, name: "MIDNIGHT_SILVER", server: 9},
            {index: 11, name: "CAST_IRON_SIL", server: 10},
            {index: 12, name: "RED", server: 27},
            {index: 13, name: "TORINO_RED", server: 28},
            {index: 14, name: "FORMULA_RED", server: 29},
            {index: 15, name: "LAVA_RED", server: 150},
            {index: 16, name: "BLAZE_RED", server: 30},
            {index: 17, name: "GRACE_RED", server: 31},
            {index: 18, name: "GARNET_RED", server: 32},
            {index: 19, name: "SUNSET_RED", server: 33},
            {index: 20, name: "CABERNET_RED", server: 34},
            {index: 21, name: "WINE_RED", server: 143},
            {index: 22, name: "CANDY_RED", server: 35},
            {index: 23, name: "HOT_PINK", server: 135},
            {index: 24, name: "PINK", server: 137},
            {index: 25, name: "SALMON_PINK", server: 136},
            {index: 26, name: "SUNRISE_ORANGE", server: 36},
            {index: 27, name: "ORANGE", server: 38},
            {index: 28, name: "BRIGHT_ORANGE", server: 138},
            {index: 29, name: "GOLD", server: 37},
            {index: 30, name: "BRONZE", server: 90},
            {index: 31, name: "YELLOW", server: 88},
            {index: 32, name: "RACE_YELLOW", server: 89},
            {index: 33, name: "FLUR_YELLOW", server: 91},
            {index: 34, name: "DARK_GREEN", server: 49},
            {index: 35, name: "RACING_GREEN", server: 50},
            {index: 36, name: "SEA_GREEN", server: 51},
            {index: 37, name: "OLIVE_GREEN", server: 52},
            {index: 38, name: "BRIGHT_GREEN", server: 53},
            {index: 39, name: "PETROL_GREEN", server: 54},
            {index: 40, name: "LIME_GREEN", server: 92},
            {index: 41, name: "MIDNIGHT_BLUE", server: 141},
            {index: 42, name: "GALAXY_BLUE", server: 61},
            {index: 43, name: "DARK_BLUE", server: 62},
            {index: 44, name: "SAXON_BLUE", server: 63},
            {index: 45, name: "BLUE", server: 64},
            {index: 46, name: "MARINER_BLUE", server: 65},
            {index: 47, name: "HARBOR_BLUE", server: 66},
            {index: 48, name: "DIAMOND_BLUE", server: 67},
            {index: 49, name: "SURF_BLUE", server: 68},
            {index: 50, name: "NAUTICAL_BLUE", server: 69},
            {index: 51, name: "RACING_BLUE", server: 73},
            {index: 52, name: "ULTRA_BLUE", server: 70},
            {index: 53, name: "LIGHT_BLUE", server: 74},
            {index: 54, name: "CHOCOLATE_BROWN", server: 96},
            {index: 55, name: "BISON_BROWN", server: 101},
            {index: 56, name: "CREEK_BROWN", server: 95},
            {index: 57, name: "UMBER_BROWN", server: 94},
            {index: 58, name: "MAPLE_BROWN", server: 97},
            {index: 59, name: "BEECHWOOD_BROWN", server: 103},
            {index: 60, name: "SIENNA_BROWN", server: 104},
            {index: 61, name: "SADDLE_BROWN", server: 98},
            {index: 62, name: "MOSS_BROWN", server: 100},
            {index: 63, name: "WOODBEECH_BROWN", server: 102},
            {index: 64, name: "STRAW_BROWN", server: 99},
            {index: 65, name: "SANDY_BROWN", server: 105},
            {index: 66, name: "BLEECHED_BROWN", server: 106},
            {index: 67, name: "PURPLE", server: 71},
            {index: 68, name: "SPIN_PURPLE", server: 72},
            {index: 69, name: "MIGHT_PURPLE", server: 146},
            {index: 70, name: "BRIGHT_PURPLE", server: 145},
            {index: 71, name: "CREAM", server: 107},
            {index: 72, name: "WHITE", server: 111},
            {index: 73, name: "FROST_WHITE", server: 112}
        ]
    },

    {
        index: 3,
        name: "Matte",
        count: 20,
        colors: [
            {index: 0, name: "BLACK", server: 12},
            {index: 1, name: "GREY", server: 13},
            {index: 2, name: "LIGHT_GREY", server: 14},
            {index: 3, name: "WHITE", server: 131},
            {index: 4, name: "BLUE", server: 83},
            {index: 5, name: "DARK_BLUE", server: 82},
            {index: 6, name: "MIDNIGHT_BLUE", server: 84},
            {index: 7, name: "MIGHT_PURPLE", server: 149},
            {index: 8, name: "Purple", server: 148},
            {index: 9, name: "RED", server: 39},
            {index: 10, name: "DARK_RED", server: 40},
            {index: 11, name: "ORANGE", server: 41},
            {index: 12, name: "YELLOW", server: 42},
            {index: 13, name: "LIME_GREEN", server: 55},
            {index: 14, name: "GREEN", server: 128},
            {index: 15, name: "MATTE_FOR", server: 151},
            {index: 16, name: "MATTE_FOIL", server: 155},
            {index: 17, name: "MATTE_OD", server: 152},
            {index: 18, name: "MATTE_DIRT", server: 153},
            {index: 19, name: "MATTE_DESERT", server: 154}
        ]
    },
    
    {
        index: 4,
        name: "Metal",
        count: 5,
        colors: [
            {index: 0, name: "BR_STEEL", server: 117},
            {index: 1, name: "BR_BLACK_STEEL", server: 118},
            {index: 2, name: "BR_ALUMINIUM", server: 119},
            {index: 3, name: "GOLD_P", server: 158},
            {index: 4, name: "GOLD_S", server: 159}
        ]
    },
    
    {
        index: 5,
        name: "Chrome",
        count: 1,
        colors: [
            {index: 0, name: "CHROME", server: 120}
        ]
    },

    {
        index: 6,
        name: "Chameleon",
        count: 10,
        colors: [
            {index: 0, name: "ANOD_RED", server: 161},
            {index: 1, name: "ANOD_BLUE", server: 164},
            {index: 2, name: "ANOD_GOLD", server: 170},
            {index: 3, name: "GREEN_BLUE_FLIP", server: 171},
            {index: 4, name: "PURP_GREEN_FLIP", server: 183},
            {index: 5, name: "ORANG_PURP_FLIP", server: 191},
            {index: 6, name: "DARKPURPLEPEARL", server: 199},
            {index: 7, name: "BLUE_PEARL", server: 209},
            {index: 8, name: "RED_PRISMA", server: 216},
            {index: 9, name: "BLACK_PRISMA", server: 218}
        ]
    }
]