files = [
	"stream/assets/*"
]

[meta]
"stream/carcols.meta" = "CARCOLS_FILE"
"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
"stream/handling.meta" = "HANDLING_FILE"
"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"

"stream/audio/sfx/dlc_toysupmk4" = "AUDIO_WAVEPACK"
"stream/audio/toysupmk4_game.dat" = "AUDIO_GAMEDATA"
"stream/audio/toysupmk4_sounds.dat" = "AUDIO_SOUNDDATA"
#"stream/audio/toysupmk4_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
"toysupmk4" = "Toyota Supra"