files = [
	"stream/assets/*"
]

[meta]
	"stream/carcols.meta" = "CARCOLS_FILE"
	"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
	"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
	"stream/handling.meta" = "HANDLING_FILE"
	"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"
	# "stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"

	"stream/audio/sfx/dlc_lg28cst26b" = "AUDIO_WAVEPACK"
	"stream/audio/lg28cst26b_game.dat" = "AUDIO_GAMEDATA"
	"stream/audio/lg28cst26b_sounds.dat" = "AUDIO_SOUNDDATA"
	# "stream/audio/lg28cst26b_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
	"787b" = "Mazda 787B"
