files = [
	"stream/assets/*"
]

[meta]
"stream/carcols.meta" = "CARCOLS_FILE"
"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
"stream/handling.meta" = "HANDLING_FILE"
#"stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"
"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"

"stream/audio/sfx/dlc_bnr34ffeng" = "AUDIO_WAVEPACK"
"stream/audio/bnr34ffeng_game.dat" = "AUDIO_GAMEDATA"
"stream/audio/bnr34ffeng_sounds.dat" = "AUDIO_SOUNDDATA"
"stream/audio/bnr34ffeng_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
"SkylineGTR" = "Nissan Skyline GTR"