files = [
	"stream/assets/*"
]

[meta]
	"stream/carcols.meta" = "CARCOLS_FILE"
	"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
	"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
	"stream/handling.meta" = "HANDLING_FILE"
	#"stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"
	"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"

	"stream/audio/sfx/dlc_aventadorv12" = "AUDIO_WAVEPACK"
	"stream/audio/aventadorv12_game.dat" = "AUDIO_GAMEDATA"
	"stream/audio/aventadorv12_sounds.dat" = "AUDIO_SOUNDDATA"
	"stream/audio/aventadorv12_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
	"lp770" = "Lamborghini Centenario"
