files = [
	"stream/assets/*"
]

[meta]
	"stream/carcols.meta" = "CARCOLS_FILE"
	"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
	"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
	"stream/handling.meta" = "HANDLING_FILE"
	"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"
	"stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"

	"stream/audio/sfx/dlc_f20c" = "AUDIO_WAVEPACK"
	"stream/audio/f20c_game.dat" = "AUDIO_GAMEDATA"
	"stream/audio/f20c_sounds.dat" = "AUDIO_SOUNDDATA"
	# "stream/audio/f20c_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
	"FK8" = "Honda Civic Type-R"
