
export const vehicleList = {
    huracan_spyder: 'huracans',
    huracan_p: 'huracanp',
    r8_2008: 'r8',
    r8_2016: 'r8v10',
    chiron: '2017chiron',
    chiron_ss: '2019chiron',
    giulia_gta: 'gtam21',
    giulia: 'giulia',
    skyline: 'Skyline',
    countach: 'lpi8004',
    r6: 'r6',
    italia_458: 'italia458',
    centenario: 'lp770',
    mustang_gt: 'MGT',
    
}

export const wheelTypeList = ["Sport", "Muscle", "Lowrider", "SUV", "Tout Terrain", "Tuner", "Moto", /*"Haut de Gamme"*/"Luxe", "Rue", /*"Rue Rouillés"*/"Rue", "Circuit", "Tunning 1", "Tunning 2"]

export const modList = [
    "Spoilers",
    "Front Bumper",
    "Rear Bumper",
    "Side skirt",
    "Exhaust",
    "Frame",
    "Grille",
    "Bonnet",
    "Left Wing",
    "Right wing",
    "Roof",
    "Engine",
    "Brakes",
    "Transmission",
    "Horns",
    "Suspension",
    "Armor",
    "",
    "Turbo",
    "",
    "Custom tire smoke",
    "",
    "Xenon",
    "Front Wheels",
    "Back Wheels",
    "Plate holders",
    "Plate vanity",
    "Trim Design",
    "Ornaments",
    "",
    "Dial Design",
    "Door interior",
    "Seats",
    "Steering Wheel",
    "Shift Lever",
    "Plaques",
    "Rear shelf",
    "Trunk",
    "Hydraulics",
    "Engine block",
    "Air filter",
    "Strut bar",
    "Arch Cover",
    "Antenna",
    "Exterior parts",
    "Tank",
    "Door",
    "WHEELS_REAR_OR_HYDRAULICS",
    "Livery",
]

const Mod = ['supra', 'rx7', '370z', 'gt86', 'gtr', 'h2r', 's1000rr', 'i8', 'rs7', 'huracanspyder', 'huracanp', 'r8', 'r8spyder', 'p1', 'vanquish', 'chiron', 'chironss', ]
const Sport = [ 'alpha', 'banshee', 'bestiagts', 'blista2', 'blista3', 'buffalo2', 'buffalo3', 'carbonizzare', 'comet2', 'comet3', 'comet4', 'comet5', 'coquette', 'coquette4', 'drafter', 'elegy', 'elegy2', 'feltzer2', 'flashgt', 'furoregt', 'fusilade', 'futo', 'gb200', 'hotring', 'imorgon', 'issi7', 'italigto', 'italirsx', 'jester', 'jester2', 'jester3', 'jugular', 'khamelion', 'koModa', 'kuruma', 'kuruma2', 'locust', 'lynx', 'massacro', 'massacro2', 'neo', 'neon', 'ninef', 'ninef2', 'omnis', 'paragon', 'paragon2', 'pariah', 'penumbra', 'penumbra2', 'raiden', 'rapidgt', 'rapidgt2', 'raptor', 'revolter', 'ruston', 'schafter3', 'schafter4', 'schlagen', 'schwarzer', 'Schwartzer', 'sentinel3', 'seven70', 'specter', 'specter2', 'streiter', 'sugoi', 'sultan', 'sultan2', 'surano', 'tampa2', 'tropos', 'verlierer2', 'veto', 'veto2', 'vstr', 'zr380', 'zr3802', 'zr3803', ]
const SportClassic = ['ardent', 'btype', 'btype2', 'btype3', 'casco', 'cheburek', 'cheetah2', 'coquette2', 'deluxo', 'dynasty', 'fagaloa', 'feltzer3', 'gt500', 'infernus2', 'jb700', 'jb7002', 'mamba', 'manana', 'michelli', 'monroe', 'nebula', 'peyote', 'peyote3', 'pigalle', 'rapidgt3', 'retinue', 'retinue2', 'savestra', 'stinger', 'stingergt', 'stromberg', 'swinger', 'toreador', 'torero', 'tornado', 'tornado2', 'tornado3', 'tornado4', 'tornado5', 'tornado6', 'turismo2', 'viseris', 'z190', 'zion3', 'ztype', ]
const SuperCar = ['adder', 'autarch', 'banshee2', 'bullet', 'cheetah', 'cyclone', 'deveste', 'emerus', 'entity2', 'entityxf', 'fmj', 'furia', 'gp1', 'infernus', 'italigtb', 'italigtb2', 'krieger', 'le7b', 'nero', 'nero2', 'osiris', 'penetrator', 'pfister811', 'prototipo', 'reaper', 's80', 'sc1', 'scramjet', 'sheava', 'sultanrs', 't20', 'taipan', 'tempesta', 'tezeract', 'thrax', 'tigon', 'turismor', 'tyrant', 'tyrus', 'vacca', 'vagner', 'vigilante', 'visione', 'voltic', 'voltic2', 'xa21', 'zentorno', 'zorrusso', ]
const Suv = ['baller', 'baller2', 'baller3', 'baller4', 'baller5', 'baller6', 'bjxl', 'cavalcade', 'cavalcade2', 'contender', 'dubsta', 'dubsta2', 'fq2', 'granger', 'gresley', 'habanero', 'huntley', 'landstalker', 'landstalker2', 'mesa', 'mesa2', 'novak', 'patriot', 'patriot2', 'radi', 'rebla', 'rocoto', 'seminole', 'seminole2', 'serrano', 'squaddie', 'toros', 'xls', 'xls2', ]
const Van = ['bison', 'bison2', 'bison3', 'bobcatxl', 'boxville', 'boxville2', 'boxville3', 'boxville4', 'boxville5', 'burrito', 'burrito2', 'burrito3', 'burrito4', 'burrito5', 'camper', 'gburrito', 'gburrito2', 'journey', 'minivan', 'minivan2', 'paradise', 'pony', 'pony2', 'rumpo', 'rumpo2', 'rumpo3', 'speedo', 'speedo2', 'speedo4', 'surfer', 'surfer2', 'taco', 'youga', 'youga2', 'youga3', ]
const Muscle = ['blade', 'buccaneer', 'buccaneer2', 'chino', 'chino2', 'clique', 'coquette3', 'deviant', 'dominator', 'dominator2', 'dominator3', 'dominator4', 'dominator5', 'dominator6', 'dukes', 'dukes2', 'dukes3', 'ellie', 'faction', 'faction2', 'faction3', 'gauntlet', 'gauntlet2', 'gauntlet3', 'gauntlet4', 'gauntlet5', 'hermes', 'hotknife', 'hustler', 'impaler', 'impaler2', 'impaler3', 'impaler4', 'imperator', 'imperator2', 'imperator3', 'lurcher', 'manana2', 'moonbeam', 'moonbeam2', 'nightshade', 'peyote2', 'phoenix', 'picador', 'ratloader', 'ratloader2', 'ruiner', 'ruiner2', 'ruiner3', 'sabregt', 'sabregt2', 'slamvan', 'slamvan2', 'slamvan3', 'slamvan4', 'slamvan5', 'slamvan6', 'stalion', 'stalion2', 'tampa', 'tampa3', 'tulip', 'vamos', 'vigero', 'virgo', 'virgo2', 'virgo3', 'voodoo', 'voodoo2', 'yosemite', 'yosemite2', ]
const Offroad = ['bfinjection', 'bifta', 'blazer', 'blazer2', 'blazer3', 'blazer4', 'blazer5', 'bodhi2', 'brawler', 'bruiser', 'bruiser2', 'bruiser3', 'brutus', 'brutus2', 'brutus3', 'caracara', 'caracara2', 'dloader', 'dubsta3', 'mphipster', 'dune', 'dune2', 'dune3', 'dune4', 'dune5', 'everon', 'freecrawler', 'hellion', 'insurgent', 'insurgent2', 'insurgent3', 'kalahari', 'kamacho', 'marshall', 'menacer', 'mesa3', 'monster', 'monster3', 'monster4', 'monster5', 'nightshark', 'outlaw', 'rancherxl', 'rancherxl2', 'rcbandito', 'rebel', 'rebel2', 'riata', 'sandking', 'sandking2', 'technical', 'technical2', 'technical3', 'trophytruck', 'trophytruck2', 'vagrant', 'verus', 'winky', 'yosemite3', 'zhaba', ]
const Sedan = ['asea', 'asea2', 'asterope', 'cog55', 'cog552', 'cognoscenti', 'cognoscenti2', 'emperor', 'emperor2', 'emperor3', 'fugitive', 'glendale', 'glendale2', 'ingot', 'intruder', 'limo2', 'premier', 'primo', 'primo2', 'regina', 'romero', 'schafter2', 'schafter5', 'schafter6', 'stafford', 'stanier', 'stratum', 'stretch', 'superd', 'surge', 'tailgater', 'warrener', 'washington', ]
const Coupe = ['cogcabrio', 'exemplar', 'f620', 'felon', 'felon2', 'jackal', 'oracle', 'oracle2', 'sentinel', 'sentinel2', 'windsor', 'windsor2', 'zion', 'zion2', ]
const Compact = ['asbo', 'blista', 'brioso', 'club', 'dilettante', 'dilettante2', 'issi2', 'kanjo', 'panto', 'prairie', 'rhapsody', 'brioso2', 'issi3', 'issi4', 'issi5', 'issi6', 'weevil', ]
const Cycle = ['bmx', 'cruiser', 'fixter', 'scorcher', 'tribike', 'tribike2', 'tribike3', ]
const Emergency = ['ambulance', 'fbi', 'fbi2', 'firetruk', 'lguard', 'pbus', 'police', 'police2', 'police3', 'police4', 'policeb', 'policeold1', 'policeold2', 'policet', 'pranger', 'riot', 'riot2', 'sheriff', 'sheriff2', ]
const Helicopter = ['akula', 'annihilator', 'annihilator2', 'buzzard', 'buzzard2', 'cargobob', 'cargobob2', 'cargobob3', 'cargobob4', 'frogger', 'frogger2', 'havok', 'hunter', 'maverick', 'polmav', 'savage', 'seasparrow', 'seasparrow2', 'seasparrow3', 'skylift', 'supervolito', 'supervolito2', 'swift', 'swift2', 'valkyrie', 'valkyrie2', 'volatus', ]
const Plane = ['alkonost', 'alphaz1', 'avenger', 'avenger2', 'bestra', 'blimp', 'blimp2', 'blimp3', 'bombushka', 'cargoplane', 'cuban800', 'dodo', 'duster', 'howard', 'hydra', 'jet', 'lazer', 'luxor', 'luxor2', 'mammatus', 'microlight', 'miljet', 'mogul', 'molotok', 'nimbus', 'nokota', 'pyro', 'rogue', 'sealbreeze', 'shamal', 'starling', 'strikeforce', 'stunt', 'titan', 'tula', 'velum', 'velum2', 'vestra', 'volatol', ]
const Boat = ['avisa', 'dinghy', 'dinghy2', 'dinghy3', 'dinghy4', 'dinghy5', 'jetmax', 'kosatka', 'longfin', 'marquis', 'patrolboat', 'predator', 'seashark', 'seashark2', 'seashark3', 'speeder', 'speeder2', 'squalo', 'submersible', 'submersible2', 'suntrap', 'toro', 'toro2', 'tropic', 'tropic2', 'tug', ]
const Industrial = ['bulldozer', 'cutter', 'dump', 'flatbed', 'guardian', 'handler', 'mixer', 'mixer2', 'rubble', 'tiptruck', 'tiptruck2', ]
const Service = ['aribus', 'brickade', 'bus', 'coach', 'pbus2', 'rallytruck', 'rentalbus', 'taxi', 'tourbus', 'trash', 'trash2', 'wastelander', ]
const Commercial = ['benson', 'biff', 'cerberus', 'cerberus2', 'cerberus3', 'hauler', 'hauler2', 'mule', 'mule2', 'mule3', 'mule4', 'packer', 'phantom', 'phantom2', 'phantom3', 'pounder', 'pounder2', 'stockade', 'stockade3', 'terbyte', ]
const Military = ['apc', 'barracks', 'barracks2', 'barracks3', 'barrage', 'chernobog', 'crusader', 'halftrack', 'khanjali', 'minitank', 'rhino', 'scarab', 'scarab2', 'scarab3', 'thruster', 'trailersmall2', 'vetir', ]
const Motorcycle = ['akuma', 'avarus', 'bagger', 'bati', 'bati2', 'bf400', 'carbonrs', 'chimera', 'cliffhanger', 'daemon', 'daemon2', 'deathbike', 'deathbike2', 'deathbike3', 'defiler', 'diablous', 'diablous2', 'double', 'enduro', 'esskey', 'faggio', 'faggio2', 'faggio3', 'fcr', 'fcr2', 'gargoyle', 'hakuchou', 'hakuchou2', 'hexer', 'innovation', 'lectro', 'manchez', 'manchez2', 'nemesis', 'nightblade', 'oppressor', 'oppressor2', 'pcj', 'ratbike', 'rrocket', 'ruffian', 'sanchez', 'sanchez2', 'sanctus', 'shotaro', 'sovereign', 'stryder', 'thrust', 'vader', 'vindicator', 'vortex', 'wolfsbane', 'zombiea', 'zombieb', ]
const F1 = ['formula', 'formula2', 'openwheel1', 'openwheel2', ]
export let vehList = { Mod: Mod, Sport: Sport, SportClassic: SportClassic, Supercar: SuperCar, Suv: Suv, Van: Van, Muscle: Muscle, Offroad: Offroad, Sedan: Sedan, Coupe: Coupe, Compact: Compact, Motorcycle: Motorcycle, F1: F1, Cycle: Cycle, Emergency: Emergency, Helicopter: Helicopter, Plane: Plane, Boat: Boat, Industrial: Industrial, Service: Service, Commercial: Commercial, Military: Military}


export const colors = [
    {
        //  typeIndex: 0,
        name: "Normal",
        count: 75,
        colors: [
            {"index":0,"name":"BLACK"},
            {"index":1,"name":"BLACK_GRAPHITE"},
            {"index":2,"name":"GRAPHITE"},
            {"index":3,"name":"ANTHR_BLACK"},
            {"index":4,"name":"BLACK_STEEL"},
            {"index":5,"name":"DARK_SILVER"},
            {"index":6,"name":"SILVER"},
            {"index":7,"name":"BLUE_SILVER"},
            {"index":8,"name":"ROLLED_STEEL"},
            {"index":9,"name":"SHADOW_SILVER"},
            {"index":10,"name":"STONE_SILVER"},
            {"index":11,"name":"MIDNIGHT_SILVER"},
            {"index":12,"name":"CAST_IRON_SIL"},
            {"index":13,"name":"RED"},
            {"index":14,"name":"TORINO_RED"},
            {"index":15,"name":"FORMULA_RED"},
            {"index":16,"name":"LAVA_RED"},
            {"index":17,"name":"BLAZE_RED"},
            {"index":18,"name":"GRACE_RED"},
            {"index":19,"name":"GARNET_RED"},
            {"index":20,"name":"SUNSET_RED"},
            {"index":21,"name":"CABERNET_RED"},
            {"index":22,"name":"WINE_RED"},
            {"index":23,"name":"CANDY_RED"},
            {"index":24,"name":"HOT_PINK"},
            {"index":25,"name":"PINK"},
            {"index":26,"name":"SALMON_PINK"},
            {"index":27,"name":"SUNRISE_ORANGE"},
            {"index":28,"name":"ORANGE"},
            {"index":29,"name":"BRIGHT_ORANGE"},
            {"index":30,"name":"GOLD"},
            {"index":31,"name":"BRONZE"},
            {"index":32,"name":"YELLOW"},
            {"index":33,"name":"RACE_YELLOW"},
            {"index":34,"name":"FLUR_YELLOW"},
            {"index":35,"name":"DARK_GREEN"},
            {"index":36,"name":"RACING_GREEN"},
            {"index":37,"name":"SEA_GREEN"},
            {"index":38,"name":"OLIVE_GREEN"},
            {"index":39,"name":"BRIGHT_GREEN"},
            {"index":40,"name":"PETROL_GREEN"},
            {"index":41,"name":"LIME_GREEN"},
            {"index":42,"name":"MIDNIGHT_BLUE"},
            {"index":43,"name":"GALAXY_BLUE"},
            {"index":44,"name":"DARK_BLUE"},
            {"index":45,"name":"SAXON_BLUE"},
            {"index":46,"name":"BLUE"},
            {"index":47,"name":"MARINER_BLUE"},
            {"index":48,"name":"HARBOR_BLUE"},
            {"index":49,"name":"DIAMOND_BLUE"},
            {"index":50,"name":"SURF_BLUE"},
            {"index":51,"name":"NAUTICAL_BLUE"},
            {"index":52,"name":"RACING_BLUE"},
            {"index":53,"name":"ULTRA_BLUE"},
            {"index":54,"name":"LIGHT_BLUE"},
            {"index":55,"name":"CHOCOLATE_BROWN"},
            {"index":56,"name":"BISON_BROWN"},
            {"index":57,"name":"CREEK_BROWN"},
            {"index":58,"name":"UMBER_BROWN"},
            {"index":59,"name":"MAPLE_BROWN"},
            {"index":60,"name":"BEECHWOOD_BROWN"},
            {"index":61,"name":"SIENNA_BROWN"},
            {"index":62,"name":"SADDLE_BROWN"},
            {"index":63,"name":"MOSS_BROWN"},
            {"index":64,"name":"WOODBEECH_BROWN"},
            {"index":65,"name":"STRAW_BROWN"},
            {"index":66,"name":"SANDY_BROWN"},
            {"index":67,"name":"BLEECHED_BROWN"},
            {"index":68,"name":"PURPLE"},
            {"index":69,"name":"SPIN_PURPLE"},
            {"index":70,"name":"MIGHT_PURPLE"},
            {"index":71,"name":"BRIGHT_PURPLE"},
            {"index":72,"name":"CREAM"},
            {"index":73,"name":"WHITE"},
            {"index":74,"name":"FROST_WHITE"}
        ]
    },
    
    {
        //  typeIndex: 1,
        name: "Metallic",
        count: 75,
        colors: [
            {"index":0,"name":"BLACK"},
            {"index":1,"name":"BLACK_GRAPHITE"},
            {"index":2,"name":"GRAPHITE"},
            {"index":3,"name":"ANTHR_BLACK"},
            {"index":4,"name":"BLACK_STEEL"},
            {"index":5,"name":"DARK_SILVER"},
            {"index":6,"name":"SILVER"},
            {"index":7,"name":"BLUE_SILVER"},
            {"index":8,"name":"ROLLED_STEEL"},
            {"index":9,"name":"SHADOW_SILVER"},
            {"index":10,"name":"STONE_SILVER"},
            {"index":11,"name":"MIDNIGHT_SILVER"},
            {"index":12,"name":"CAST_IRON_SIL"},
            {"index":13,"name":"RED"},
            {"index":14,"name":"TORINO_RED"},
            {"index":15,"name":"FORMULA_RED"},
            {"index":16,"name":"LAVA_RED"},
            {"index":17,"name":"BLAZE_RED"},
            {"index":18,"name":"GRACE_RED"},
            {"index":19,"name":"GARNET_RED"},
            {"index":20,"name":"SUNSET_RED"},
            {"index":21,"name":"CABERNET_RED"},
            {"index":22,"name":"WINE_RED"},
            {"index":23,"name":"CANDY_RED"},
            {"index":24,"name":"HOT_PINK"},
            {"index":25,"name":"PINK"},
            {"index":26,"name":"SALMON_PINK"},
            {"index":27,"name":"SUNRISE_ORANGE"},
            {"index":28,"name":"ORANGE"},
            {"index":29,"name":"BRIGHT_ORANGE"},
            {"index":30,"name":"GOLD"},
            {"index":31,"name":"BRONZE"},
            {"index":32,"name":"YELLOW"},
            {"index":33,"name":"RACE_YELLOW"},
            {"index":34,"name":"FLUR_YELLOW"},
            {"index":35,"name":"DARK_GREEN"},
            {"index":36,"name":"RACING_GREEN"},
            {"index":37,"name":"SEA_GREEN"},
            {"index":38,"name":"OLIVE_GREEN"},
            {"index":39,"name":"BRIGHT_GREEN"},
            {"index":40,"name":"PETROL_GREEN"},
            {"index":41,"name":"LIME_GREEN"},
            {"index":42,"name":"MIDNIGHT_BLUE"},
            {"index":43,"name":"GALAXY_BLUE"},
            {"index":44,"name":"DARK_BLUE"},
            {"index":45,"name":"SAXON_BLUE"},
            {"index":46,"name":"BLUE"},
            {"index":47,"name":"MARINER_BLUE"},
            {"index":48,"name":"HARBOR_BLUE"},
            {"index":49,"name":"DIAMOND_BLUE"},
            {"index":50,"name":"SURF_BLUE"},
            {"index":51,"name":"NAUTICAL_BLUE"},
            {"index":52,"name":"RACING_BLUE"},
            {"index":53,"name":"ULTRA_BLUE"},
            {"index":54,"name":"LIGHT_BLUE"},
            {"index":55,"name":"CHOCOLATE_BROWN"},
            {"index":56,"name":"BISON_BROWN"},
            {"index":57,"name":"CREEK_BROWN"},
            {"index":58,"name":"UMBER_BROWN"},
            {"index":59,"name":"MAPLE_BROWN"},
            {"index":60,"name":"BEECHWOOD_BROWN"},
            {"index":61,"name":"SIENNA_BROWN"},
            {"index":62,"name":"SADDLE_BROWN"},
            {"index":63,"name":"MOSS_BROWN"},
            {"index":64,"name":"WOODBEECH_BROWN"},
            {"index":65,"name":"STRAW_BROWN"},
            {"index":66,"name":"SANDY_BROWN"},
            {"index":67,"name":"BLEECHED_BROWN"},
            {"index":68,"name":"PURPLE"},
            {"index":69,"name":"SPIN_PURPLE"},
            {"index":70,"name":"MIGHT_PURPLE"},
            {"index":71,"name":"BRIGHT_PURPLE"},
            {"index":72,"name":"CREAM"},
            {"index":73,"name":"WHITE"},
            {"index":74,"name":"FROST_WHITE"}
        ]
    },

    {
        //  typeIndex: 2,
        name: "Pearl",
        count: 74,
        colors: [
            {"type":2,"index":0,"name":"BLACK"},
            {"type":2,"index":1,"name":"BLACK"},
            {"type":2,"index":2,"name":"BLACK"},
            {"type":2,"index":3,"name":"BLACK"},
            {"type":2,"index":4,"name":"BLACK"},
            {"type":2,"index":5,"name":"BLACK"},
            {"type":2,"index":6,"name":"BLACK"},
            {"type":2,"index":7,"name":"BLACK"},
            {"type":2,"index":8,"name":"BLACK"},
            {"type":2,"index":9,"name":"BLACK"},
            {"type":2,"index":10,"name":"BLACK"},
            {"type":2,"index":11,"name":"BLACK"},
            {"type":2,"index":12,"name":"BLACK"},
            {"type":2,"index":13,"name":"BLACK"},
            {"type":2,"index":14,"name":"BLACK"},
            {"type":2,"index":15,"name":"BLACK"},
            {"type":2,"index":16,"name":"BLACK"},
            {"type":2,"index":17,"name":"BLACK"},
            {"type":2,"index":18,"name":"BLACK"},
            {"type":2,"index":19,"name":"BLACK"},
            {"type":2,"index":20,"name":"BLACK"},
            {"type":2,"index":21,"name":"BLACK"},
            {"type":2,"index":22,"name":"BLACK"},
            {"type":2,"index":23,"name":"BLACK"},
            {"type":2,"index":24,"name":"BLACK"},
            {"type":2,"index":25,"name":"BLACK"},
            {"type":2,"index":26,"name":"BLACK"},
            {"type":2,"index":27,"name":"BLACK"},
            {"type":2,"index":28,"name":"BLACK"},
            {"type":2,"index":29,"name":"BLACK"},
            {"type":2,"index":30,"name":"BLACK"},
            {"type":2,"index":31,"name":"BLACK"},
            {"type":2,"index":32,"name":"BLACK"},
            {"type":2,"index":33,"name":"BLACK"},
            {"type":2,"index":34,"name":"BLACK"},
            {"type":2,"index":35,"name":"BLACK"},
            {"type":2,"index":36,"name":"BLACK"},
            {"type":2,"index":37,"name":"BLACK"},
            {"type":2,"index":38,"name":"BLACK"},
            {"type":2,"index":39,"name":"BLACK"},
            {"type":2,"index":40,"name":"BLACK"},
            {"type":2,"index":41,"name":"BLACK"},
            {"type":2,"index":42,"name":"BLACK"},
            {"type":2,"index":43,"name":"BLACK"},
            {"type":2,"index":44,"name":"BLACK"},
            {"type":2,"index":45,"name":"BLACK"},
            {"type":2,"index":46,"name":"BLACK"},
            {"type":2,"index":47,"name":"BLACK"},
            {"type":2,"index":48,"name":"BLACK"},
            {"type":2,"index":49,"name":"BLACK"},
            {"type":2,"index":50,"name":"BLACK"},
            {"type":2,"index":51,"name":"BLACK"},
            {"type":2,"index":52,"name":"BLACK"},
            {"type":2,"index":53,"name":"BLACK"},
            {"type":2,"index":54,"name":"BLACK"},
            {"type":2,"index":55,"name":"BLACK"},
            {"type":2,"index":56,"name":"BLACK"},
            {"type":2,"index":57,"name":"BLACK"},
            {"type":2,"index":58,"name":"BLACK"},
            {"type":2,"index":59,"name":"BLACK"},
            {"type":2,"index":60,"name":"BLACK"},
            {"type":2,"index":61,"name":"BLACK"},
            {"type":2,"index":62,"name":"BLACK"},
            {"type":2,"index":63,"name":"BLACK"},
            {"type":2,"index":64,"name":"BLACK"},
            {"type":2,"index":65,"name":"BLACK"},
            {"type":2,"index":66,"name":"BLACK"},
            {"type":2,"index":67,"name":"BLACK"},
            {"type":2,"index":68,"name":"BLACK"},
            {"type":2,"index":69,"name":"BLACK"},
            {"type":2,"index":70,"name":"BLACK"},
            {"type":2,"index":71,"name":"BLACK"},
            {"type":2,"index":72,"name":"BLACK"},
            {"type":2,"index":73,"name":"BLACK"}
        ]
    },

    {
        //  typeIndex: 3,
        name: "Matte",
        count: 20,
        colors: [
            {"index":0,"name":"BLACK"},
            {"index":1,"name":"GREY"},
            {"index":2,"name":"LIGHT_GREY"},
            {"index":3,"name":"WHITE"},
            {"index":4,"name":"BLUE"},
            {"index":5,"name":"DARK_BLUE"},
            {"index":6,"name":"MIDNIGHT_BLUE"},
            {"index":7,"name":"MIGHT_PURPLE"},
            {"index":8,"name":"Purple"},
            {"index":9,"name":"RED"},
            {"index":10,"name":"DARK_RED"},
            {"index":11,"name":"ORANGE"},
            {"index":12,"name":"YELLOW"},
            {"index":13,"name":"LIME_GREEN"},
            {"index":14,"name":"GREEN"},
            {"index":15,"name":"MATTE_FOR"},
            {"index":16,"name":"MATTE_FOIL"},
            {"index":17,"name":"MATTE_OD"},
            {"index":18,"name":"MATTE_DIRT"},
            {"index":19,"name":"MATTE_DESERT"}
        ]
    },
    
    {
        //  typeIndex: 4,
        name: "Metal",
        count: 5,
        colors: [
            {"index":0,"name":"BR_STEEL"},
            {"index":1,"name":"BR_BLACK_STEEL"},
            {"index":2,"name":"BR_ALUMINIUM"},
            {"index":3,"name":"GOLD_P"},
            {"index":4,"name":"GOLD_S"}
        ]
    },
    
    {
        //  typeIndex: 5,
        name: "Chrome",
        count: 1,
        colors: [
            {"index":0,"name":"CHROME"},
        ]
    },

    {
        //  typeIndex: 6,
        name: "Chameleon",
        count: 10,
        colors: [
            {"index":0,"name":"ANOD_RED"},
            {"index":1,"name":"ANOD_BLUE"},
            {"index":2,"name":"ANOD_GOLD"},
            {"index":3,"name":"GREEN_BLUE_FLIP"},
            {"index":4,"name":"PURP_GREEN_FLIP"},
            {"index":5,"name":"ORANG_PURP_FLIP"},
            {"index":6,"name":"DARKPURPLEPEARL"},
            {"index":7,"name":"BLUE_PEARL"},
            {"index":8,"name":"RED_PRISMA"},
            {"index":9,"name":"BLACK_PRISMA"}
        ]
    }
]
