files = [
	"stream/assets/*"
]

[meta]
	"stream/carcols.meta" = "CARCOLS_FILE"
	"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
	"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
	"stream/handling.meta" = "HANDLING_FILE"
	"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"
	# "stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"

	"stream/audio/sfx/dlc_ferrarif140fe" = "AUDIO_WAVEPACK"
	"stream/audio/ferrarif140fe_game.dat" = "AUDIO_GAMEDATA"
	"stream/audio/ferrarif140fe_sounds.dat" = "AUDIO_SOUNDDATA"
	# "stream/audio/ferrarif140fe_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
	"laferrari" = "La Ferrari"
