files = [
	"stream/assets/*"
]

[meta]
"stream/carcols.meta" = "CARCOLS_FILE"
"stream/carvariations.meta" = "VEHICLE_VARIATION_FILE"
"stream/dlctext.meta" = "VEHICLE_VARIATION_FILE"
"stream/handling.meta" = "HANDLING_FILE"
#"stream/vehiclelayouts.meta" = "VEHICLE_LAYOUTS_FILE"
"stream/vehicles.meta" = "VEHICLE_METADATA_FILE"

"stream/audio/sfx/dlc_ta103ninjah2r" = "AUDIO_WAVEPACK"
"stream/audio/ta103ninjah2r_game.dat" = "AUDIO_GAMEDATA"
"stream/audio/ta103ninjah2r_sounds.dat" = "AUDIO_SOUNDDATA"
"stream/audio/ta103ninjah2r_amp.dat" = "AUDIO_SYNTHDATA"

[gxt]
"ninjah2" = "Kawasaki H2R"